// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGnY-kKZ2Kv84dYJ9R6TB97Q_9kQriBKs',
    appId: '1:842945362863:web:accc909efc00f67c9a8d5a',
    messagingSenderId: '842945362863',
    projectId: 'kiddio-ccb98',
    authDomain: 'kiddio-ccb98.firebaseapp.com',
    storageBucket: 'kiddio-ccb98.firebasestorage.app',
    measurementId: 'G-P47YJ52346',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtMHlI7QDvV8IgpLA8oTdigextANQX50',
    appId: '1:842945362863:android:9e5f2a3b6d3869999a8d5a',
    messagingSenderId: '842945362863',
    projectId: 'kiddio-ccb98',
    storageBucket: 'kiddio-ccb98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ICb6g7gfqD1eZ-AmSK5IiSIB8UoirlY',
    appId: '1:842945362863:ios:dc2e40b6642843fd9a8d5a',
    messagingSenderId: '842945362863',
    projectId: 'kiddio-ccb98',
    storageBucket: 'kiddio-ccb98.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ICb6g7gfqD1eZ-AmSK5IiSIB8UoirlY',
    appId: '1:842945362863:ios:dc2e40b6642843fd9a8d5a',
    messagingSenderId: '842945362863',
    projectId: 'kiddio-ccb98',
    storageBucket: 'kiddio-ccb98.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGnY-kKZ2Kv84dYJ9R6TB97Q_9kQriBKs',
    appId: '1:842945362863:web:206291d019da122d9a8d5a',
    messagingSenderId: '842945362863',
    projectId: 'kiddio-ccb98',
    authDomain: 'kiddio-ccb98.firebaseapp.com',
    storageBucket: 'kiddio-ccb98.firebasestorage.app',
    measurementId: 'G-82F6X9F2BX',
  );
}
