// Placeholder firebase_options.dart
// This file is normally generated by the FlutterFire CLI (`flutterfire configure`).
// Run `flutter pub global activate flutterfire_cli` and
// `flutter pub global run flutterfire_cli configure` to generate
// a real `lib/firebase_options.dart` for your Firebase project.

import 'package:firebase_core/firebase_core.dart';

/// Placeholder implementation that throws a clear error if used at runtime.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => throw UnsupportedError(
      'DefaultFirebaseOptions is not configured. Run `flutterfire configure` to generate `lib/firebase_options.dart`.\n'
      'See README.md for instructions.');
}
